Update notes to avoid Qt build errors
Saw this in Debian 12 (trixie/sid) but may apply to macOS too.

If Qt5 and Qt6 are both installed, then when `make` runs `qmake`,
it can bring in Qt5 headers and break the build with errors like:

```
qt/mAMainWindow.cpp: In constructor ‘mAMainWindow::mAMainWindow(QWidget*)’:
qt/mAMainWindow.cpp:136:36: error: invalid use of incomplete type ‘class QScreen’
  136 |     QRect available = primaryScreen->availableGeometry();
      |                                    ^~
```

(Fixing this `#include` just leads to a "successful" build that crashes at startup
due to qtscintilla not matching the Qt SDK.)